// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: blocks.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockProducer_Blocks_FullMethodName = "/blocks.BlockProducer/Blocks"
)

// BlockProducerClient is the client API for BlockProducer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockProducerClient interface {
	Blocks(ctx context.Context, in *InitBlock, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
}

type blockProducerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockProducerClient(cc grpc.ClientConnInterface) BlockProducerClient {
	return &blockProducerClient{cc}
}

func (c *blockProducerClient) Blocks(ctx context.Context, in *InitBlock, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockProducer_ServiceDesc.Streams[0], BlockProducer_Blocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InitBlock, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockProducer_BlocksClient = grpc.ServerStreamingClient[Block]

// BlockProducerServer is the server API for BlockProducer service.
// All implementations must embed UnimplementedBlockProducerServer
// for forward compatibility.
type BlockProducerServer interface {
	Blocks(*InitBlock, grpc.ServerStreamingServer[Block]) error
	mustEmbedUnimplementedBlockProducerServer()
}

// UnimplementedBlockProducerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockProducerServer struct{}

func (UnimplementedBlockProducerServer) Blocks(*InitBlock, grpc.ServerStreamingServer[Block]) error {
	return status.Errorf(codes.Unimplemented, "method Blocks not implemented")
}
func (UnimplementedBlockProducerServer) mustEmbedUnimplementedBlockProducerServer() {}
func (UnimplementedBlockProducerServer) testEmbeddedByValue()                       {}

// UnsafeBlockProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockProducerServer will
// result in compilation errors.
type UnsafeBlockProducerServer interface {
	mustEmbedUnimplementedBlockProducerServer()
}

func RegisterBlockProducerServer(s grpc.ServiceRegistrar, srv BlockProducerServer) {
	// If the following call pancis, it indicates UnimplementedBlockProducerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockProducer_ServiceDesc, srv)
}

func _BlockProducer_Blocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitBlock)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockProducerServer).Blocks(m, &grpc.GenericServerStream[InitBlock, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockProducer_BlocksServer = grpc.ServerStreamingServer[Block]

// BlockProducer_ServiceDesc is the grpc.ServiceDesc for BlockProducer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockProducer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blocks.BlockProducer",
	HandlerType: (*BlockProducerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Blocks",
			Handler:       _BlockProducer_Blocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blocks.proto",
}
