// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.1
// source: chain_cursor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *StartCursor) Reset() {
	*x = StartCursor{}
	mi := &file_chain_cursor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCursor) ProtoMessage() {}

func (x *StartCursor) ProtoReflect() protoreflect.Message {
	mi := &file_chain_cursor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCursor.ProtoReflect.Descriptor instead.
func (*StartCursor) Descriptor() ([]byte, []int) {
	return file_chain_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *StartCursor) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_chain_cursor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_chain_cursor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_chain_cursor_proto_rawDescGZIP(), []int{1}
}

func (x *Cursor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_chain_cursor_proto protoreflect.FileDescriptor

var file_chain_cursor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x22, 0x32, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x4b, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x73,
	0x12, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x1a, 0x14, 0x2e, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x68, 0x72, 0x69, 0x73, 0x2d, 0x64, 0x65, 0x2d, 0x6c, 0x65, 0x6f, 0x6e, 0x2f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chain_cursor_proto_rawDescOnce sync.Once
	file_chain_cursor_proto_rawDescData = file_chain_cursor_proto_rawDesc
)

func file_chain_cursor_proto_rawDescGZIP() []byte {
	file_chain_cursor_proto_rawDescOnce.Do(func() {
		file_chain_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(file_chain_cursor_proto_rawDescData)
	})
	return file_chain_cursor_proto_rawDescData
}

var file_chain_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chain_cursor_proto_goTypes = []any{
	(*StartCursor)(nil), // 0: chain_cursor.StartCursor
	(*Cursor)(nil),      // 1: chain_cursor.Cursor
}
var file_chain_cursor_proto_depIdxs = []int32{
	0, // 0: chain_cursor.ChainCursor.Cursors:input_type -> chain_cursor.StartCursor
	1, // 1: chain_cursor.ChainCursor.Cursors:output_type -> chain_cursor.Cursor
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chain_cursor_proto_init() }
func file_chain_cursor_proto_init() {
	if File_chain_cursor_proto != nil {
		return
	}
	file_chain_cursor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chain_cursor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_cursor_proto_goTypes,
		DependencyIndexes: file_chain_cursor_proto_depIdxs,
		MessageInfos:      file_chain_cursor_proto_msgTypes,
	}.Build()
	File_chain_cursor_proto = out.File
	file_chain_cursor_proto_rawDesc = nil
	file_chain_cursor_proto_goTypes = nil
	file_chain_cursor_proto_depIdxs = nil
}
