// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: chain_cursor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChainCursor_Cursors_FullMethodName = "/chain_cursor.ChainCursor/Cursors"
)

// ChainCursorClient is the client API for ChainCursor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainCursorClient interface {
	Cursors(ctx context.Context, in *StartCursor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cursor], error)
}

type chainCursorClient struct {
	cc grpc.ClientConnInterface
}

func NewChainCursorClient(cc grpc.ClientConnInterface) ChainCursorClient {
	return &chainCursorClient{cc}
}

func (c *chainCursorClient) Cursors(ctx context.Context, in *StartCursor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cursor], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChainCursor_ServiceDesc.Streams[0], ChainCursor_Cursors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartCursor, Cursor]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainCursor_CursorsClient = grpc.ServerStreamingClient[Cursor]

// ChainCursorServer is the server API for ChainCursor service.
// All implementations must embed UnimplementedChainCursorServer
// for forward compatibility.
type ChainCursorServer interface {
	Cursors(*StartCursor, grpc.ServerStreamingServer[Cursor]) error
	mustEmbedUnimplementedChainCursorServer()
}

// UnimplementedChainCursorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainCursorServer struct{}

func (UnimplementedChainCursorServer) Cursors(*StartCursor, grpc.ServerStreamingServer[Cursor]) error {
	return status.Errorf(codes.Unimplemented, "method Cursors not implemented")
}
func (UnimplementedChainCursorServer) mustEmbedUnimplementedChainCursorServer() {}
func (UnimplementedChainCursorServer) testEmbeddedByValue()                     {}

// UnsafeChainCursorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainCursorServer will
// result in compilation errors.
type UnsafeChainCursorServer interface {
	mustEmbedUnimplementedChainCursorServer()
}

func RegisterChainCursorServer(s grpc.ServiceRegistrar, srv ChainCursorServer) {
	// If the following call pancis, it indicates UnimplementedChainCursorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainCursor_ServiceDesc, srv)
}

func _ChainCursor_Cursors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartCursor)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainCursorServer).Cursors(m, &grpc.GenericServerStream[StartCursor, Cursor]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainCursor_CursorsServer = grpc.ServerStreamingServer[Cursor]

// ChainCursor_ServiceDesc is the grpc.ServiceDesc for ChainCursor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainCursor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain_cursor.ChainCursor",
	HandlerType: (*ChainCursorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Cursors",
			Handler:       _ChainCursor_Cursors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chain_cursor.proto",
}
